/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const PotButton: typeof import('@potati/components')['PotButton']
  const PotIcon: typeof import('@potati/components')['PotIcon']
  const PotRadio: typeof import('@potati/components')['PotRadio']
}
