/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const PotButton: typeof import('@potati/components/es')['PotButton']
  const PotIcon: typeof import('@potati/components/es')['PotIcon']
  const PotRadio: typeof import('@potati/components/es')['PotRadio']
}
