/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const PotButton: typeof import('@potati/components')['PotButton']
  const PotInput: typeof import('@potati/components')['PotInput']
}
