/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PotButton: typeof import('@potati/components')['PotButton']
    PotInput: typeof import('@potati/components')['PotInput']
  }
}
